### ISSUE TITLE
Create tests :/

### ISSUE THREAD

**Issue by guiferpa** [stone-payments/gcd#13]
Create tests for cases in __gcd__ environment

**Comment by amirkarimi** [comment]
Can you please confirm the test flow:

1. Run a docker container which stops automatically
2. Run the gcd
3. Check if the docker image is deleted

If make sense I'll start working on this.

**Comment by guiferpa** [comment]
@amirkarimi ,

#### So so, I want use this cases that you did write and some cases like I explain below:

Check some environments with different parameter values, by example:

If pass __true__ to __-remove-healthy-containers-exited__, I need verify if removed all containers with status not equal 0 and containers exited with status equal 0.

Sorry my english, but anything that you not understand let me know...

**Comment by amirkarimi** [comment]
@guiferpa Thanks for the explanation. I'll start working on that.

**Comment by amirkarimi** [comment]
Done #14

**Comment by guiferpa** [comment]
Great, tks @amirkarimi
