### ISSUE TITLE
Create support for HTTP/HTTPS integration with Docker API

### ISSUE THREAD

**Issue by guiferpa** [stone-payments/gcd#15]
Today the __gcd__ use only connection by _docker.sock_, this issue is for implements support by HTTP/HTTPS connection

**Comment by josledp** [comment]
I was trying to look at this issue, but running gcd with:
-docker-host=http://127.0.0.1:2375

works for me. Could you describe the issue further please?

**Comment by guiferpa** [comment]
Fine, sorry I did not explain very well. I think about remove dependencie go-dockerclient and create a custom Docker client package with connection support __unix://__ and __http://__ and only requests that gcd need.
